### ISSUE TITLE
device_requests field dropped when multiple yml files specified

### ISSUE THREAD

**Issue by proximous** [beehiveai/compose#1]
issue moved from https://github.com/docker/compose/issues/6691#issuecomment-685869907

@visheratin see this example, am I wrong to expect a different result?

docker-compose.nogpu.yml:
```
version: '3.8'

services:
  df:
    build: miniconda-image.Dockerfile
```
docker-compose.gpu.yml:
```
version: '3.8'

services:
  df:
    build: nvidia-image.Dockerfile
    device_requests:
      - capabilities:
          - gpu
```
use only the nogpu.yml:
```
$ docker-compose -f docker-compose.nogpu.yml config
services:
  df:
    build:
      context: /home/jerry/gpu-test/miniconda-image.Dockerfile
version: '3'
```
use only the gpu.yml:
```
$ docker-compose -f docker-compose.gpu.yml config
services:
  df:
    build:
      context: /home/jerry/gpu-test/nvidia-image.Dockerfile
    device_requests:
    - capabilities:
      - gpu
version: '3'
```
chain config ymls starting with a non-gpu yml (note...missing the runtime):
```
$ docker-compose -f docker-compose.nogpu.yml -f docker-compose.gpu.yml config
services:
  df:
    build:
      context: /home/jerry/gpu-test/nvidia-image.Dockerfile
version: '3'
```

expected output:
```
$ docker-compose -f docker-compose.nogpu.yml -f docker-compose.gpu.yml config
services:
  df:
    build:
      context: /home/jerry/gpu-test/nvidia-image.Dockerfile
    device_requests:
      - capabilities:
          - gpu
version: '3'
```

(Obviously I'm trying to something more elaborate and this is just a simplified case to highlight the unexpected behavior.)
